stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - data/raw/heart_disease_uci.csv
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - data/processed/scaler.joblib
      - data/processed/feature_names.json

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    outs:
      - models/champion_model.joblib
      - models/logisticregression_model.joblib
      - models/randomforest_model.joblib
      - models/xgboost_model.joblib
    metrics:
      - models/champion_info.json:
          cache: false
